<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>cn.cangjiecloud</groupId>
        <artifactId>cangjie-agent</artifactId>
        <version>1.0.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <artifactId>cangjie-service</artifactId>
    <packaging>pom</packaging>
    <name>${project.artifactId}</name>
    <modules>
        <module>cangjie-user</module>
        <module>cangjie-model</module>
        <module>cangjie-knowledge</module>
        <module>cangjie-tool</module>
        <module>cangjie-application</module>
        <module>cangjie-workflow</module>
        <module>cangjie-trigger</module>
        <module>cangjie-observability</module>
        <module>cangjie-oss</module>
        <module>cangjie-system</module>
        <module>cangjie-chat</module>
        <module>cangjie-prompt</module>
    </modules>
</project>

